-- ARCHIVIATO DA S05 — NON ESEGUIRE.
--
-- Questo script verificava il titolare del Giro confrontando un PIN conservato
-- in chiaro nella tabella dipendenti. La funzione è stata sostituita dalla Edge
-- Function verify-giro-owner-pin, che delega la verifica a Supabase Auth.
--
-- La rimozione definitiva della vecchia funzione database è contenuta in:
-- migrations_manual/2026-09-04_s05_remove_plaintext_pin.sql
