import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'node:path';
import fs from 'node:fs';
const dom=new JSDOM('<div id="root"></div>',{url:'https://test.invalid'});
for(const key of ['window','document','navigator','HTMLElement','HTMLInputElement','localStorage','Event','MouseEvent']) Object.defineProperty(globalThis,key,{configurable:true,value:dom.window[key]});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});
const React=await import('react'); const {createRoot}=await import('react-dom/client'); const {act}=React;
const server=await createServer({configFile:false,plugins:[react()],optimizeDeps:{noDiscovery:true},server:{middlewareMode:true},resolve:{alias:[{find:/(?:.*\/lib\/supabase|\.\/supabase)(?:\.js)?$/,replacement:path.resolve('tests/fixtures/fleetSupabase.js')}]}});
const {default:Page}=await server.ssrLoadModule('/src/pages/AutomezziPage.jsx');
const {ToastProvider}=await server.ssrLoadModule('/src/components/Toast.jsx');
const {fixture}=await server.ssrLoadModule('/tests/fixtures/fleetSupabase.js');
const root=createRoot(document.getElementById('root'));
const settle=async()=>act(async()=>{await new Promise(r=>setTimeout(r,100));});
const button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===text);
const click=async element=>{assert.ok(element);assert.equal(element.disabled,false);await act(async()=>element.click());await settle();};
let captured,closed=false;
window.open=()=>({document:{body:{innerHTML:''}},location:{replace(){}},close(){closed=true;}});
const originalURL=URL.createObjectURL, originalTimeout=globalThis.setTimeout;
URL.createObjectURL=blob=>{captured=blob;return originalURL(blob);};
globalThis.setTimeout=(fn,ms,...args)=>{const timer=originalTimeout(fn,ms,...args);if(ms===300000)timer.unref();return timer;};
try {
 await act(async()=>root.render(React.createElement(ToastProvider,null,React.createElement(Page))));await settle();
 await click(button('PDF MEZZI'));assert.equal(document.querySelectorAll('input[type=checkbox]:checked').length,2);
 await click(button('Deseleziona tutti'));assert.equal(button('APRI PDF').disabled,true);
 await click(document.querySelector('input[type=checkbox]'));
 const search=document.querySelector('[placeholder="Cerca mezzo o targa…"]');
 await act(async()=>{Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value').set.call(search,'Fiorino');search.dispatchEvent(new window.Event('input',{bubbles:true}));});await settle();
 assert.equal(document.querySelectorAll('input[type=checkbox]').length,1);assert.match(document.body.textContent,/1 selezionati/);
 fixture.records.push({id:'r2',vehicle_id:'one',km:121234,work_date:'2020-01-02'});
 const calls=fixture.calls.length;await click(button('APRI PDF'));assert.ok(captured);assert.ok(fixture.calls.length>calls);
 fs.writeFileSync('/tmp/fleet-ui.pdf',Buffer.from(await captured.arrayBuffer()));
 captured=null;await click(button('PDF MEZZI'));fixture.fail=true;await click(button('APRI PDF'));
 assert.equal(captured,null);assert.equal(closed,true);assert.match(document.body.textContent,/Dati non aggiornati/);
 console.log('PASS UI: popup, tutti/nessuno, filtro senza perdere selezione, rilettura prima del PDF, errore blocca export.');
} finally {await act(async()=>root.unmount());await server.close();dom.window.close();URL.createObjectURL=originalURL;globalThis.setTimeout=originalTimeout;}
