import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'node:path';
import fs from 'node:fs';
const dom = new JSDOM('<!DOCTYPE html><html><head></head><body><div id="root"></div></body></html>', { url: 'https://local-test.invalid/' });
for (const key of ['window','document','navigator','HTMLElement','HTMLInputElement','HTMLDialogElement','localStorage','sessionStorage','Event','MouseEvent']) Object.defineProperty(globalThis, key, { configurable: true, value: dom.window[key] });
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
window.matchMedia = () => ({ matches: false, addEventListener() {}, removeEventListener() {} });
window.scrollTo = () => {};
window.HTMLCanvasElement.prototype.getContext = () => null;
window.HTMLDialogElement.prototype.showModal = function() { this.open = true; };
window.HTMLDialogElement.prototype.close = function() { this.open = false; };
const React = await import('react');
const { createRoot } = await import('react-dom/client');
const { act } = React;
const server = await createServer({ configFile: false, plugins: [react()], optimizeDeps: { noDiscovery: true }, server: { middlewareMode: true }, resolve: { alias: [{ find: /(?:.*\/lib\/supabase|\.\/supabase)(?:\.js)?$/, replacement: path.resolve('tests/fixtures/officeSupabase.js') }] } });
const { default: App } = await server.ssrLoadModule('/src/App.jsx');
const { fixture } = await server.ssrLoadModule('/tests/fixtures/officeSupabase.js');
const root = createRoot(document.getElementById('root'));
const settle = async (ms = 80) => { await act(async () => { await new Promise(r => setTimeout(r, ms)); }); };
const click = async element => { assert.ok(element, 'Expected control exists'); assert.equal(element.disabled, false); await act(async () => { element.click(); }); await settle(); };
const button = text => [...document.querySelectorAll('button')].find(b => b.textContent.trim() === text);
const fill = async (input, value) => { await act(async () => { Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value').set.call(input,value);input.dispatchEvent(new window.Event('input',{bubbles:true})); }); };
function savePreview(name) {
  if (!process.argv.includes('--preview')) return;
  const cssFile = fs.readdirSync('dist/assets').find(f => f.endsWith('.css'));
  const font = fs.readFileSync('public/fonts/manrope-latin-variable.woff2').toString('base64');
  const css = fs.readFileSync(`dist/assets/${cssFile}`, 'utf8').replaceAll('/fonts/manrope-latin-variable.woff2', `data:font/woff2;base64,${font}`);
  fs.mkdirSync('docs', { recursive: true });
  const body = document.getElementById('root').innerHTML.replace(/src="\/([^\"]+)"/g, (match, name) => {
    const file = path.join('public', name);
    return fs.existsSync(file) ? `src="data:image/png;base64,${fs.readFileSync(file).toString('base64')}"` : match;
  });
  fs.writeFileSync(`docs/${name}.html`, `<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Play Money 14 · Anteprima dimostrativa</title><style>${css}</style><body><div id="root">${body}</div><div style="position:fixed;bottom:6px;right:12px;z-index:100;background:#33291e;color:#ecd8b3;padding:7px 12px;border-radius:8px;font:10px system-ui">ANTEPRIMA STATICA · DATI DIMOSTRATIVI</div></body></html>`);
}
try {
  await act(async () => root.render(React.createElement(App)));
  await settle(1200);
  await click(document.querySelector('.office-sidebar-link'));
  assert.equal(document.querySelector('.office-error')?.textContent, undefined);
  assert.match(document.querySelector('.office-total').textContent, /11\.500/);
  assert.equal(document.querySelectorAll('.office-component').length, 4);
  await click(document.querySelector('[aria-label="Modifica Fondo Cassa"]'));
  await fill(document.querySelector('dialog input'), '10.000');
  await act(async () => document.querySelector('dialog form').dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true })));
  await settle();
  assert.equal(fixture.fund.amount, 10000);
  assert.match(document.querySelector('.office-total').textContent, /21\.500/);
  assert.match(document.querySelector('.office-sidebar-amount').textContent, /21\.500/);
  savePreview('ANTEPRIMA_CASSA_15');
  await click(document.querySelector('[aria-label="Apri contabilità ultimo periodo chiuso"]'));
  assert.equal(document.querySelector('[aria-label="Periodo contabilità"]').value, 'closed');
  assert.match(document.querySelector('.office-ledger-total').textContent, /10\.000/);
  await click(button('Aggiungi movimento'));
  await fill(document.querySelector('dialog input.money'), '500');
  await fill(document.querySelectorAll('dialog input')[1], 'Spesa di prova');
  await act(async () => document.querySelector('dialog form').dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true })));
  await settle();
  assert.equal(fixture.manual.length, 1);
  assert.equal(fixture.manual[0].period_id, 'closed');
  assert.match(document.querySelector('.office-ledger-total').textContent, /9\.500/);
  assert.match(document.querySelector('.office-sidebar-amount').textContent, /21\.000/);
  await click(document.querySelector('[aria-label="Modifica Spesa di prova"]'));
  await fill(document.querySelector('dialog input.money'), '600');
  await act(async () => document.querySelector('dialog form').dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true })));
  await settle();
  assert.equal(fixture.manual.length, 1); assert.equal(fixture.manual[0].amount, 600);
  assert.match(document.querySelector('.office-ledger-total').textContent, /9\.400/);
  savePreview('ANTEPRIMA_CONTABILITA_15');
  await click(document.querySelector('.office-back'));
  assert.match(document.body.textContent, /30\/08\/2026 — 16\/09\/2026/);
  await click(button('CONTABILITÀ CONTEGGI'));
  assert.equal(document.querySelector('[aria-label="Periodo contabilità"]').value, 'closed');
  assert.equal(fixture.calls.filter(x => x.operation === 'insert' && x.table === 'contabilita_conteggi_righe').length, 1);
  console.log('UI OK: authenticated App/provider, sidebar, four fields, fund save + synced total, closed-period navigation, add/edit without duplicate, return to same archived Conteggi period.');
} finally { await act(async () => root.unmount()); await server.close(); dom.window.close(); }
