import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'node:path';
const dom = new JSDOM('<html><body><div id="root"></div></body></html>', { url:'https://local-test.invalid/' });
for (const key of ['window','document','navigator','HTMLElement','HTMLInputElement','HTMLTextAreaElement','localStorage','sessionStorage','Event','MouseEvent']) Object.defineProperty(globalThis, key, { configurable:true, value:dom.window[key] });
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const React = await import('react');
const { act } = React;
const { createRoot } = await import('react-dom/client');
const server = await createServer({ configFile:false, plugins:[react()], optimizeDeps:{noDiscovery:true}, server:{middlewareMode:true}, resolve:{alias:[{find:/(?:.*\/lib\/supabase|\.\/supabase)(?:\.js)?$/,replacement:path.resolve('tests/fixtures/officeSupabase.js')}] } });
const { SlotManagementModal } = await server.ssrLoadModule('/src/pages/LocaliPage.jsx');
const root = createRoot(document.getElementById('root'));
let saved;
const onSave = async (rows,note) => { saved = {rows,note}; };
const render = async props => { await act(async()=>root.render(React.createElement(SlotManagementModal,{open:true,onClose:()=>{},onSave,...props}))); };
const click = async element => { assert.ok(element); assert.equal(element.disabled,false); await act(async()=>element.click()); };
const input = async (element,value) => { await act(async()=>{ const proto = element.tagName === 'TEXTAREA' ? window.HTMLTextAreaElement.prototype : window.HTMLInputElement.prototype; Object.getOwnPropertyDescriptor(proto,'value').set.call(element,value); element.dispatchEvent(new window.Event('input',{bubbles:true})); }); };
try {
  const slots = [{model:'QUEEN 1',quantity:8},{model:'MARIM TOUCH',quantity:1}];
  await render({slots,note:'Fondo cassa 500 €'});
  assert.equal(document.querySelector('#slot-note').value,'Fondo cassa 500 €');
  assert.equal(document.querySelector('[aria-label="Quantità MARIK TOUCH"]').value,'1');
  await click(document.querySelector('[aria-label="Riduci QUEEN 1"]'));
  await click(document.querySelector('[aria-label="Aumenta QUEEN 2"]'));
  await input(document.querySelector('#slot-note'),'Fondo cassa 700 €\nNota del locale');
  await click([...document.querySelectorAll('button')].find(b=>b.textContent === 'SALVA SLOT E NOTE'));
  assert.deepEqual(saved, {rows:[{model:'QUEEN 1',quantity:7},{model:'QUEEN 2',quantity:1},{model:'MARIK TOUCH',quantity:1}],note:'Fondo cassa 700 €\nNota del locale'});
  await render({open:false,slots});
  await render({slots:[],note:'Nota di un altro locale'});
  assert.equal(document.querySelector('#slot-note').value,'Nota di un altro locale');
  assert.equal(document.querySelector('[aria-label="Quantità QUEEN 1"]').value,'0');
  await input(document.querySelector('[aria-label="Quantità JACK"]'),'1.5');
  saved = null;
  await click([...document.querySelectorAll('button')].find(b=>b.textContent === 'SALVA SLOT E NOTE'));
  assert.equal(saved,null);
  assert.match(document.body.textContent,/numeri interi/);
  await render({open:false});
  await render({slots:[],onSave:async()=>{throw new Error('Errore di rete di prova');}});
  await input(document.querySelector('#slot-note'),'La bozza resta qui');
  await click([...document.querySelectorAll('button')].find(b=>b.textContent === 'SALVA SLOT E NOTE'));
  assert.match(document.body.textContent,/Errore di rete di prova/);
  assert.equal(document.querySelector('#slot-note').value,'La bozza resta qui');
  console.log('Interfaccia Slot: cambio quantità 0→1, nota, cambio locale, interi e errore di rete verificati.');
} finally { await act(async()=>root.unmount()); await server.close(); dom.window.close(); }
