import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
const admin='00000000-0000-0000-0000-000000000001', employee='00000000-0000-0000-0000-000000000002';
const period='10000000-0000-0000-0000-000000000001', other='10000000-0000-0000-0000-000000000002', count='20000000-0000-0000-0000-000000000001';
await db.exec(`create role anon; create role authenticated; create schema auth;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create function public.is_play_money_admin() returns boolean language sql stable as $$select auth.uid()='${admin}'::uuid$$;
grant usage on schema auth to authenticated;
create table conteggi_periods(id uuid primary key);
create table conteggi_tool(id uuid primary key,period_id uuid references conteggi_periods,debito numeric);
insert into conteggi_periods values('${period}'),('${other}'); insert into conteggi_tool values('${count}','${period}',250);
grant select on conteggi_periods,conteggi_tool to authenticated;`);
await db.exec(fs.readFileSync('supabase/migrations_manual/2026-08-27_contabilita_conteggi.sql','utf8'));
const sql=fs.readFileSync('supabase/migrations/20261001161638_admin_v18_contabilita_conteggi.sql','utf8');
await db.exec(sql); await db.exec(sql);
const role=async who=>db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${who}',false)`);
const save=async (p,rows)=>db.query('select admin_v18_save_accounting_debts($1,$2::jsonb)',[p,JSON.stringify(rows)]);
await role(admin);
await save(period,[{conteggio_id:count,amount_override:125.5}]);
assert.equal(Number((await db.query('select amount_override from contabilita_conteggi_debiti_selezionati')).rows[0].amount_override),125.5);
assert.equal(Number((await db.query('select debito from conteggi_tool')).rows[0].debito),250);
for(const value of [-1,1000000000,0.001]) await assert.rejects(save(period,[{conteggio_id:count,amount_override:value}]));
await assert.rejects(save(other,[{conteggio_id:count,amount_override:100}]));
await assert.rejects(save(period,[{conteggio_id:count},{conteggio_id:count}]));
assert.equal(Number((await db.query('select amount_override from contabilita_conteggi_debiti_selezionati')).rows[0].amount_override),125.5);
await save(period,[{conteggio_id:count,amount_override:0}]);
assert.equal(Number((await db.query('select amount_override from contabilita_conteggi_debiti_selezionati')).rows[0].amount_override),0);
await save(period,[{conteggio_id:count,amount_override:null}]);
assert.equal((await db.query('select amount_override from contabilita_conteggi_debiti_selezionati')).rows[0].amount_override,null);
await role(employee); await assert.rejects(save(period,[])); assert.equal((await db.query('select * from contabilita_conteggi_debiti_selezionati')).rows.length,0);
await role(admin);await save(period,[]);assert.equal((await db.query('select * from contabilita_conteggi_debiti_selezionati')).rows.length,0);
await db.exec('reset role;set role anon');await assert.rejects(save(period,[]));
await db.close(); console.log('PASS: SQL idempotente, salvataggio atomico, isolamento periodo, originali invariati, ripristino, zero/centesimi, RLS admin e anon.');
