import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
const admin='00000000-0000-0000-0000-000000000001', employee='00000000-0000-0000-0000-000000000002', id='10000000-0000-0000-0000-000000000001';
await db.exec(`create role anon; create role authenticated; create schema auth;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create function public.is_play_money_admin_secure() returns boolean language sql stable as $$select auth.uid()='${admin}'::uuid$$;
grant usage on schema auth to authenticated,anon;
create table venues(id text primary key,name text); insert into venues values('K51','Approdo'),('K52','Altro');
create table debiti(id uuid primary key default gen_random_uuid(),venue_id text references venues(id),importo_iniziale numeric,residuo numeric,modalita text,periodicita text,rata_tipo text,rata_importo numeric,status text,note text,created_at timestamptz default now(),updated_at timestamptz default now());
create table debiti_movimenti(id uuid primary key default gen_random_uuid(),debito_id uuid references debiti(id) on delete cascade,venue_id text,data date,user_id uuid,operator_name text,importo numeric,residuo_prima numeric,residuo_dopo numeric,origine text,note text,created_at timestamptz default now(),conteggio_id uuid);
alter table debiti enable row level security; alter table debiti_movimenti enable row level security;
create policy debt_admin on debiti for all to authenticated using(public.is_play_money_admin_secure()) with check(public.is_play_money_admin_secure());
create policy movement_admin on debiti_movimenti for all to authenticated using(public.is_play_money_admin_secure()) with check(public.is_play_money_admin_secure());
grant select,insert,update,delete on all tables in schema public to authenticated;
insert into debiti(id,venue_id,importo_iniziale,residuo,modalita,periodicita,rata_tipo,status,created_at) values('${id}','K51',3000,1848,'contanti','ogni_conteggio','tutto_aggio','attivo','2026-09-01');
insert into debiti_movimenti(debito_id,venue_id,data,importo,residuo_prima,residuo_dopo,origine) values('${id}','K51','2026-09-08',1152,3000,1848,'conteggio');`);
const sql = fs.readFileSync(new URL('../../supabase/migrations/20260916175917_admin_v13_debiti_erogazioni.sql',import.meta.url),'utf8');
await db.exec(sql); await db.exec(sql);
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${admin}',false);`);
const current=async()=> (await db.query('select to_jsonb(d) r from debiti d where id=$1',[id])).rows[0].r;
const save=async(expected,added=500,patch={},date='2026-09-16')=>(await db.query('select admin_v13_save_debito($1,$2,$3,$4,$5) r',[id,expected,patch,added,date])).rows[0].r;
const repay=async(expected,amount,date='2026-09-16')=>(await db.query('select admin_v13_rimborso_debito($1,$2,$3,$4) r',[id,expected,amount,date])).rows[0].r;
const original=await current(); assert.equal(original.importo_originario,3000);
const added=await save(original); assert.equal(added.importo_originario,3000); assert.equal(added.importo_iniziale,3500); assert.equal(added.residuo,2348);
assert.equal((await db.query('select count(*) n from debiti_erogazioni')).rows[0].n,1);
await assert.rejects(save(original),/cambiato/);
await assert.rejects(repay(added,2349),/non superiore/);
await assert.rejects(save(added,-1),/non valida/);
await assert.rejects(save(added,1.5),/non valida/);
await assert.rejects(save(added,500,{},'2026-08-01'),/Data/);
await assert.rejects(save(added,0,{importo_iniziale:4500}),/Nuova erogazione/);
await assert.rejects(save(added,0,{venue_id:'K52'}),/locale/);
assert.deepEqual(await current(),added);
const closed=await repay(added,2348); assert.equal(closed.residuo,0); assert.equal(closed.status,'estinto');
assert.equal((await db.query('select sum(importo) n from debiti_movimenti')).rows[0].n,'3500');
const reopened=await save(closed,250); assert.equal(reopened.status,'attivo'); assert.equal(reopened.residuo,250);
await assert.rejects(repay(closed,10),/cambiato/);
// Atomic rollback if movement insertion fails.
await db.exec("reset role; alter table debiti_movimenti add constraint test_reject check(importo<>13); set role authenticated;");
await assert.rejects(repay(reopened,13),/test_reject/); assert.deepEqual(await current(),reopened);
const newId='10000000-0000-0000-0000-000000000002';
const create=venue=>db.query('select admin_v13_save_debito($1,null,$2,0,$3) r',[newId,{venue_id:venue,importo_iniziale:1000,modalita:'bonifico'},'2026-09-16']);
await assert.rejects(create('K51'),/altro debito attivo/); await create('K52');
await assert.rejects(create('K52'));
await db.query("select set_config('request.jwt.claim.sub',$1,false)",[employee]);
await assert.rejects(save(reopened,100),/riservata/); await assert.rejects(repay(reopened,100),/riservata/);
assert.equal((await db.query('select * from debiti_erogazioni')).rows.length,0);
await db.exec('reset role; set role anon;'); await assert.rejects(save(reopened,100),/permission denied/);
// New disbursements follow debt deletion, no orphaned ledger.
await db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${admin}',false); delete from debiti where id='${id}';`);
assert.equal((await db.query('select count(*) n from debiti_erogazioni')).rows[0].n,0);
await db.close(); console.log('PASS: migrazione ripetibile, saldi, erogazioni, rimborsi, atomicità, concorrenza ottimistica, RLS e cancellazione.');
