export const RELEASE = Object.freeze({
  VERSION: "19.8",
  TITLE: "Novità della versione",
  ITEMS: ["DEBITI E BONUS: NUOVA RICERCA RAPIDA CON FILTRO IMMEDIATO E SCORCIATOIA DA TASTIERA"],
});
export const APP_VERSION = RELEASE.VERSION;
