export const RELEASE = Object.freeze({
  VERSION: "19.9",
  TITLE: "Novità della versione",
  ITEMS: ["CASSA: NUOVO RIEPILOGO DEI DA RIPORTARE DISPONIBILI PER LOCALE ACCANTO A LISTA MOVIMENTI"],
});
export const APP_VERSION = RELEASE.VERSION;
